// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CleanupRules(arg1) {
  return window['go']['main']['App']['CleanupRules'](arg1);
}

export function DefaultCleanup() {
  return window['go']['main']['App']['DefaultCleanup']();
}

export function DefaultEmotion() {
  return window['go']['main']['App']['DefaultEmotion']();
}

export function EmotionRules(arg1) {
  return window['go']['main']['App']['EmotionRules'](arg1);
}

export function ExportDefaultCleanup() {
  return window['go']['main']['App']['ExportDefaultCleanup']();
}

export function ExportDefaultEmotion() {
  return window['go']['main']['App']['ExportDefaultEmotion']();
}

export function FetchVoices() {
  return window['go']['main']['App']['FetchVoices']();
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportVoicesCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportVoicesCSV'](arg1, arg2);
}

export function LoadVoices(arg1) {
  return window['go']['main']['App']['LoadVoices'](arg1);
}

export function PickCleanupFile() {
  return window['go']['main']['App']['PickCleanupFile']();
}

export function PickEmotionFile() {
  return window['go']['main']['App']['PickEmotionFile']();
}

export function PickOutputDir() {
  return window['go']['main']['App']['PickOutputDir']();
}

export function PickSourceFile() {
  return window['go']['main']['App']['PickSourceFile']();
}

export function PickVoicesFile() {
  return window['go']['main']['App']['PickVoicesFile']();
}

export function Preview(arg1) {
  return window['go']['main']['App']['Preview'](arg1);
}

export function PreviewVoice(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewVoice'](arg1, arg2, arg3);
}

export function RevealOutput(arg1) {
  return window['go']['main']['App']['RevealOutput'](arg1);
}

export function SaveCleanup(arg1, arg2) {
  return window['go']['main']['App']['SaveCleanup'](arg1, arg2);
}

export function SaveEmotion(arg1, arg2) {
  return window['go']['main']['App']['SaveEmotion'](arg1, arg2);
}

export function SaveKey(arg1) {
  return window['go']['main']['App']['SaveKey'](arg1);
}

export function SaveVoices(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveVoices'](arg1, arg2, arg3);
}

export function ScanForCleanup(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanForCleanup'](arg1, arg2, arg3);
}

export function TestCleanup(arg1, arg2) {
  return window['go']['main']['App']['TestCleanup'](arg1, arg2);
}

export function TestEmotion(arg1, arg2) {
  return window['go']['main']['App']['TestEmotion'](arg1, arg2);
}
