// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {synth} from '../models';
import {voice} from '../models';

export function Cancel():Promise<void>;

export function DefaultCleanup():Promise<main.CleanupInfo>;

export function ExportDefaultCleanup():Promise<main.CleanupInfo>;

export function FetchVoices():Promise<Array<synth.Voice>>;

export function Generate(arg1:main.Request):Promise<main.RunSummary>;

export function GetAccount():Promise<main.AccountInfo>;

export function GetSettings():Promise<main.Settings>;

export function ImportVoicesCSV(arg1:string,arg2:string):Promise<main.VoicesInfo>;

export function LoadVoices(arg1:string):Promise<main.VoicesInfo>;

export function PickCleanupFile():Promise<main.CleanupInfo>;

export function PickOutputDir():Promise<string>;

export function PickSourceFile():Promise<string>;

export function PickVoicesFile():Promise<string>;

export function Preview(arg1:main.Request):Promise<main.Preview>;

export function RevealOutput(arg1:string):Promise<void>;

export function SaveKey(arg1:string):Promise<string>;

export function SaveVoices(arg1:string,arg2:Array<voice.Assignment>,arg3:Array<voice.Slot>):Promise<main.VoicesInfo>;
