// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function FetchVoices() {
  return window['go']['main']['App']['FetchVoices']();
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportVoicesCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportVoicesCSV'](arg1, arg2);
}

export function LoadVoices(arg1) {
  return window['go']['main']['App']['LoadVoices'](arg1);
}

export function PickOutputDir() {
  return window['go']['main']['App']['PickOutputDir']();
}

export function PickSourceFile() {
  return window['go']['main']['App']['PickSourceFile']();
}

export function PickVoicesFile() {
  return window['go']['main']['App']['PickVoicesFile']();
}

export function Preview(arg1) {
  return window['go']['main']['App']['Preview'](arg1);
}

export function RevealOutput(arg1) {
  return window['go']['main']['App']['RevealOutput'](arg1);
}

export function SaveKey(arg1) {
  return window['go']['main']['App']['SaveKey'](arg1);
}
